### ISSUE TITLE
codegen error : Server not starting 

### ISSUE THREAD

**Issue by vvvprabhakar** [ExpediaDotCom/haystack-ui#544]
node -v
v11.10.1

npm -v
6.7.0

npm run start:dev  --verbose

Output
```
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node',
npm verb cli   '/usr/local/bin/npm',
npm verb cli   'run',
npm verb cli   'start:dev',
npm verb cli   '--verbose' ]
npm info using npm@6.7.0
npm info using node@v11.10.1
npm verb run-script [ 'prestart:dev', 'start:dev', 'poststart:dev' ]
npm info lifecycle haystack-ui@1.0.0~prestart:dev: haystack-ui@1.0.0
npm info lifecycle haystack-ui@1.0.0~start:dev: haystack-ui@1.0.0

> haystack-ui@1.0.0 start:dev /Users/prabhakarv/Documents/GitHub/haystack-ui
> npm run clean && npm run codegen && npm run test && concurrently -r "npm run watch" "wait-on public/bundles/report.html && npm run start:devserver"

npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'clean' ]
npm info using npm@6.7.0
npm info using node@v11.10.1
npm verb run-script [ 'preclean', 'clean', 'postclean' ]
npm info lifecycle haystack-ui@1.0.0~preclean: haystack-ui@1.0.0
npm info lifecycle haystack-ui@1.0.0~clean: haystack-ui@1.0.0

> haystack-ui@1.0.0 clean /Users/prabhakarv/Documents/GitHub/haystack-ui
> rm -rf public/bundles/ && rm -rf static_codegen

npm verb lifecycle haystack-ui@1.0.0~clean: unsafe-perm in lifecycle true
npm verb lifecycle haystack-ui@1.0.0~clean: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/prabhakarv/Documents/GitHub/haystack-ui/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/prabhakarv/Documents/GitHub/haystack-ui/node_modules/.bin:/usr/local/bin:/Users/prabhakarv/.rvm/gems/ruby-2.6.3/bin:/Users/prabhakarv/.rvm/gems/ruby-2.6.3@global/bin:/Users/prabhakarv/.rvm/rubies/ruby-2.6.3/bin:/Users/prabhakarv/.nvm/versions/node/v8.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/prabhakarv/.rvm/bin:/Users/prabhakarv/go/bin
npm verb lifecycle haystack-ui@1.0.0~clean: CWD: /Users/prabhakarv/Documents/GitHub/haystack-ui
npm info lifecycle haystack-ui@1.0.0~postclean: haystack-ui@1.0.0
npm verb exit [ 0, true ]
npm timing npm Completed in 130ms
npm info ok
npm info it worked if it ends with ok
npm verb cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'codegen' ]
npm info using npm@6.7.0
npm info using node@v11.10.1
npm verb run-script [ 'precodegen', 'codegen', 'postcodegen' ]
npm info lifecycle haystack-ui@1.0.0~precodegen: haystack-ui@1.0.0
npm info lifecycle haystack-ui@1.0.0~codegen: haystack-ui@1.0.0

> haystack-ui@1.0.0 codegen /Users/prabhakarv/Documents/GitHub/haystack-ui
> mkdir -p static_codegen && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/  ./haystack-idl/proto/span.proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/api/ -I ./haystack-idl/proto/ ./haystack-idl/proto/api/traceReader.proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/api/ -I ./haystack-idl/proto/ ./haystack-idl/proto/api/anomaly/anomalyReader.proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/api/ -I ./haystack-idl/proto/ ./haystack-idl/proto/api/subscription/subscriptionManagement.proto

/Users/prabhakarv/Documents/GitHub/haystack-ui/node_modules/grpc-tools/bin/protoc.js:41
    throw error;
    ^

Error: spawn /Users/prabhakarv/Documents/GitHub/haystack-ui/node_modules/grpc-tools/bin/protoc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:427:16)
    at processTicksAndRejections (internal/process/next_tick.js:76:17)
    at process.runNextTicks [as _tickCallback] (internal/process/next_tick.js:51:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:804:11)
    at internal/main/run_main_module.js:21:11
npm verb lifecycle haystack-ui@1.0.0~codegen: unsafe-perm in lifecycle true
npm verb lifecycle haystack-ui@1.0.0~codegen: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/prabhakarv/Documents/GitHub/haystack-ui/node_modules/.bin:/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/prabhakarv/Documents/GitHub/haystack-ui/node_modules/.bin:/usr/local/bin:/Users/prabhakarv/.rvm/gems/ruby-2.6.3/bin:/Users/prabhakarv/.rvm/gems/ruby-2.6.3@global/bin:/Users/prabhakarv/.rvm/rubies/ruby-2.6.3/bin:/Users/prabhakarv/.nvm/versions/node/v8.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/prabhakarv/.rvm/bin:/Users/prabhakarv/go/bin
npm verb lifecycle haystack-ui@1.0.0~codegen: CWD: /Users/prabhakarv/Documents/GitHub/haystack-ui
npm info lifecycle haystack-ui@1.0.0~codegen: Failed to exec codegen script
npm verb stack Error: haystack-ui@1.0.0 codegen: `mkdir -p static_codegen && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/  ./haystack-idl/proto/span.proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/api/ -I ./haystack-idl/proto/ ./haystack-idl/proto/api/traceReader.proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/api/ -I ./haystack-idl/proto/ ./haystack-idl/proto/api/anomaly/anomalyReader.proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/api/ -I ./haystack-idl/proto/ ./haystack-idl/proto/api/subscription/subscriptionManagement.proto`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:197:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:197:13)
npm verb stack     at maybeClose (internal/child_process.js:984:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
npm verb pkgid haystack-ui@1.0.0
npm verb cwd /Users/prabhakarv/Documents/GitHub/haystack-ui
npm verb Darwin 18.5.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "codegen"
npm verb node v11.10.1
npm verb npm  v6.7.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! haystack-ui@1.0.0 codegen: `mkdir -p static_codegen && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/  ./haystack-idl/proto/span.proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/api/ -I ./haystack-idl/proto/ ./haystack-idl/proto/api/traceReader.proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/api/ -I ./haystack-idl/proto/ ./haystack-idl/proto/api/anomaly/anomalyReader.proto && grpc_tools_node_protoc --js_out=import_style=commonjs,binary:./static_codegen/ --grpc_out=./static_codegen --plugin=protoc-gen-grpc=`which grpc_tools_node_protoc_plugin` -I ./haystack-idl/proto/api/ -I ./haystack-idl/proto/ ./haystack-idl/proto/api/subscription/subscriptionManagement.proto`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haystack-ui@1.0.0 codegen script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 359ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prabhakarv/.npm/_logs/2020-01-21T14_38_59_924Z-debug.log
npm verb lifecycle haystack-ui@1.0.0~start:dev: unsafe-perm in lifecycle true
npm verb lifecycle haystack-ui@1.0.0~start:dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/prabhakarv/Documents/GitHub/haystack-ui/node_modules/.bin:/usr/local/bin:/Users/prabhakarv/.rvm/gems/ruby-2.6.3/bin:/Users/prabhakarv/.rvm/gems/ruby-2.6.3@global/bin:/Users/prabhakarv/.rvm/rubies/ruby-2.6.3/bin:/Users/prabhakarv/.nvm/versions/node/v8.0.0/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/prabhakarv/.rvm/bin:/Users/prabhakarv/go/bin
npm verb lifecycle haystack-ui@1.0.0~start:dev: CWD: /Users/prabhakarv/Documents/GitHub/haystack-ui
npm info lifecycle haystack-ui@1.0.0~start:dev: Failed to exec start:dev script
npm verb stack Error: haystack-ui@1.0.0 start:dev: `npm run clean && npm run codegen && npm run test && concurrently -r "npm run watch" "wait-on public/bundles/report.html && npm run start:devserver"`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:301:16)
npm verb stack     at EventEmitter.emit (events.js:197:13)
npm verb stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
npm verb stack     at ChildProcess.emit (events.js:197:13)
npm verb stack     at maybeClose (internal/child_process.js:984:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:265:5)
npm verb pkgid haystack-ui@1.0.0
npm verb cwd /Users/prabhakarv/Documents/GitHub/haystack-ui
npm verb Darwin 18.5.0
npm verb argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start:dev" "--verbose"
npm verb node v11.10.1
npm verb npm  v6.7.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! haystack-ui@1.0.0 start:dev: `npm run clean && npm run codegen && npm run test && concurrently -r "npm run watch" "wait-on public/bundles/report.html && npm run start:devserver"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the haystack-ui@1.0.0 start:dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 1135ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/prabhakarv/.npm/_logs/2020-01-21T14_38_59_956Z-debug.log```

**Comment by bulicekj** [comment]
@vvvprabhakar thanks for letting us know. There was an issue with a dependency of grpc-tools, and is fixed now - I'm able to build and run with node v 11.10.1. Pulling down, `npm install` and `npm rebuild` should fix it for you. Let me know if you're still running into issues

**Comment by bulicekj** [comment]
Closing due to inactivity
