### ISSUE TITLE
npm install failure

### ISSUE THREAD

**Issue by ikzjfr0** [ExpediaDotCom/haystack-ui#69]
Running `npm install` in office comes following error, how to fix this:

haystack-ui git:(master) npm install

```
> canvas@1.6.7 install /Users/liangwang/Documents/Project/haystack-ui/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/liangwang/.nvm/versions/node/v8.1.2/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:336:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Darwin 16.7.0
gyp ERR! command "/Users/liangwang/.nvm/versions/node/v8.1.2/bin/node" "/Users/liangwang/.nvm/versions/node/v8.1.2/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/liangwang/Documents/Project/haystack-ui/node_modules/canvas
gyp ERR! node -v v8.1.2
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the canvas@1.6.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liangwang/.npm/_logs/2017-11-06T22_26_15_105Z-debug.log
```

**Comment by bulicekj** [comment]
Try running `sudo apt-get install libcairo2-dev libjpeg-dev libgif-dev`; I had this issue with one of our node_modules earlier as well.
